- hosts: servers
  become: yes
  tasks:
    - name: Update apt
      apt: { update_cache: yes }

    - name: Install nginx
      apt: { name: nginx, state: present }

    - name: Start nginx
      service: { name: nginx, state: started, enabled: true }
